CREATE DATABASE bd_vitoria_lanches;

use bd_vitoria_lanches;

-- CRIANDO TB_ TIPO PRODUTO 
CREATE TABLE TB_TIPO_PRODUTO
(
TB_TIPO_PRODUTO_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_TIPO_PRODUTO_DESC VARCHAR(32) NOT NULL
);

-- CRIANDO TB_PRODUTO 
CREATE TABLE TB_PRODUTO
(
TB_PRODUTO_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_PRODUTO_NOME varchar(128) NOT NULL,
TB_PRODUTO_TIPO_PRODUTO_ID INT, -- FAZER CHAVE ESTRANGEIRA DEPOIS
TB_PRODUTO_DESC VARCHAR(512) NOT NULL,
TB_PRODUTO_PREC_UNIT DECIMAL(10,2) NOT NULL,

 FOREIGN KEY (TB_PRODUTO_TIPO_PRODUTO_ID) REFERENCES TB_TIPO_PRODUTO(TB_TIPO_PRODUTO_ID)
);

-- CRIANDO TB_USERS
CREATE TABLE TB_USERS 
(
TB_USERS_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_USERS_EMAIL varchar(64) not null,
TB_USERS_SENHA VARCHAR(16) NOT NULL, 
TB_USERS_TIPO VARCHAR(16) NOT NULL
);

-- CRIANDO TB_FUNCINARIOS 
CREATE TABLE TB_FUNCINARIOS 
(
TB_FUNCINARIOS_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_FUNCINARIOS_NOME VARCHAR(128) NOT NULL,
TB_FUNCINARIOS_TEL VARCHAR(32) NOT NULL,
TB_FUNCINARIOS_ENDEREÇO VARCHAR(128) NOT NULL,
TB_FUNCINARIOS_ENDEREÇO_NUM VARCHAR(16) NOT NULL,
TB_FUNCINARIOS_SAL DECIMAL(10,2) NOT NULL,
TB_FUNCINARIOS_DATA_ADIMISSAO DATE NOT NULL
); 

-- CRIANDO TB_CLIENTE 
CREATE TABLE TB_CLIENTE 
(
TB_CLIENTE_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_CLIENTE_NOME VARCHAR(128) NOT NULL,
TB_CLIENTE_TEL VARCHAR(32) NOT NULL,
TB_CLIENTE_ENDEREÇO VARCHAR(128) NOT NULL,
TB_CLIENTE_ENDEREÇO_NUM VARCHAR(16) NOT NULL
); 

-- CRIANDO TB_PEDIDO_VENDA 
CREATE TABLE TB_PEDIDO_VENDA 
(
TB_PEDIDO_VENDA_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_PEDIDO_VENDA_CLIENTE_ID INT NOT NULL, -- FAZER CHAVE ESTRANGEIRA DEPOIS
TB_PEDIDO_VENDA_DATA DATETIME NOT NULL,
TB_PEDIDO_VENDA_VAL_TOTAL DECIMAL(10,2) NOT NULL,
TB_PEDIDO_VENDA_STATUS VARCHAR(16) NOT NULL,
TB_PEDIDO_VENDA_FORM_PAG VARCHAR(32) NOT NULL, 
TB_PEDDIDO_VENDA_OBS VARCHAR(500),

 FOREIGN KEY (TB_PEDIDO_VENDA_CLIENTE_ID) REFERENCES TB_CLIENTE(TB_CLIENTE_ID)
);

-- CRIANDO TABELA ASSOSIATIVA 7
CREATE TABLE TB_PRODUTO_PEDIDO_VENDA 
(
TB_PRODUTO_PEDIDO_VENDA_ID INT PRIMARY KEY auto_increment NOT NULL,
TB_PRODUTO_PEDIDO_VENDA_PRODUTO_ID INT NOT NULL,
TB_PRODUTO_PEDIDO_VENDA_PEDIDA_VENDA_ID INT NOT NULL,
TB_PRODUTO_PEDIDO_VENDA_QUANT INT NOT NULL,
TB_PRODUTO_PEDIDO_VENDA_PREC_UNI DECIMAL(10,2) NOT NULL,
TB_PRODUTO_PEDIDO_VENDA_PREC_TOTAL DECIMAL(10,2) NOT NULL,

 FOREIGN KEY (TB_PRODUTO_PEDIDO_VENDA_PRODUTO_ID) REFERENCES TB_PRODUTO(TB_PRODUTO_ID),
 FOREIGN KEY (TB_PRODUTO_PEDIDO_VENDA_PEDIDA_VENDA_ID) REFERENCES TB_PEDIDO_VENDA(TB_PEDIDO_VENDA_ID)

)